name: Publish to PyPI

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Set your desired Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*